/**
 * API接口常量配置
 * 自助收银系统API端点定义
 */

// API基础配置
export const API_CONFIG = {
  // 使用环境变量配置的API地址，移除硬编码逻辑
  BASE_URL: import.meta.env.VITE_API_BASE_URL?.replace('/mall-selfcheck', '') || 'http://localhost:8201',
  // 自助收银服务前缀
  SERVICE_PREFIX: '/mall-selfcheck',
  // 请求超时时间
  TIMEOUT: 10000,
  // 重试次数
  RETRY_COUNT: 3
} as const

// 完整的API基础URL
export const BASE_URL = `${API_CONFIG.BASE_URL}${API_CONFIG.SERVICE_PREFIX}`

// ===== 系统测试端点 =====
export const SYSTEM_ENDPOINTS = {
  HEALTH_CHECK: '/test/health',
  SYSTEM_INFO: '/test/info',
  AUTH_TEST: '/test/authTest',
} as const

// 请求方法类型
export const HTTP_METHODS = {
  GET: 'GET',
  POST: 'POST',
  PUT: 'PUT',
  DELETE: 'DELETE',
  PATCH: 'PATCH'
} as const

// 响应状态码
export const STATUS_CODES = {
  SUCCESS: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL_ERROR: 500,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503
} as const

// 业务错误码
export const BUSINESS_CODES = {
  SUCCESS: 200,
  FAILED: 500,
  VALIDATE_FAILED: 404,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403
} as const

/**
 * API 端点常量定义
 */

// 会员相关API
export const MEMBER_ENDPOINTS = {
  LOGIN: '/member/login',
  LOGIN_BY_CODE: '/member/loginByCode',
  GUEST_LOGIN: '/member/guestLogin',
  LOGOUT: '/member/logout',
  SEND_CODE: '/member/sendVerifyCode',
  REFRESH_ACTIVITY: '/member/refreshActivity',
  INFO: '/member/info',
  CHECK_LOGIN: '/member/checkLogin',
  GUEST_INFO: '/member/guestInfo',
  CURRENT_USER: '/member/currentUser',
  CHECK_SESSION: '/member/checkSession',
  GET_CODE: '/member/getCode',
  GENERATE_QR: '/member/generateQR',
  BALANCE_INFO: '/member/balance/info',
} as const

// 商品相关API
export const PRODUCT_ENDPOINTS = {
  LIST: '/product/list',
  DETAIL: '/product/detail',
  SEARCH: '/product/search',
  CATEGORIES: '/product/categories',
  BARCODE_SCAN: '/product/scan',
  RECOMMENDATIONS: '/product/recommendations',
  BRAND_LIST: '/product/brands',
  HOT_PRODUCTS: '/product/hot',
  NEW_PRODUCTS: '/product/new',
  PRICE_CHECK: '/product/priceCheck',
} as const

// 购物车相关API
export const CART_ENDPOINTS = {
  ADD: '/cart/add',
  REMOVE: '/cart/remove',
  UPDATE: '/cart/update',
  LIST: '/cart/list',
  CLEAR: '/cart/clear',
  COUNT: '/cart/count',
  SUMMARY: '/cart/summary',
  VALIDATE: '/cart/validate',
  AVAILABLE_COUPONS: '/cart/availableCoupons',
  CALCULATE: '/cart/calculate',
} as const

// 订单相关API
export const ORDER_ENDPOINTS = {
  CREATE: '/order/create',
  CREATE_QUICK: '/order/createQuick',
  CREATE_FROM_CART: '/order/createFromCart',
  DETAIL: '/order/detail',
  LIST: '/order/list',
  HISTORY: '/order/history',
  GUEST_HISTORY: '/order/guestHistory',
  CANCEL: '/order/cancel',
  CONFIRM: '/order/confirm',
  STATUS: '/order/status',
  CALCULATE: '/order/calculate',
  PREVIEW: '/order/preview',
  VALIDATE_STOCK: '/order/validateStock',
  PAYMENT_SUCCESS: '/order/paymentSuccess',
  PAYMENT_FAILED: '/order/paymentFailed',
} as const

// 支付相关API
export const PAYMENT_ENDPOINTS = {
  WECHAT_QR: '/selfcheck/payment/generateQR',
  ALIPAY_QR: '/selfcheck/payment/generateQR',
  SCAN_PAY: '/selfcheck/payment/scanCode',
  STATUS: '/selfcheck/payment/status',
  CANCEL: '/selfcheck/payment/cancel',
  REFUND: '/selfcheck/payment/refund',
  VALIDATE_CODE: '/selfcheck/payment/validateCode',
  DETECT_PAY_TYPE: '/selfcheck/payment/detectPayType',
} as const

// 优惠券相关API
export const COUPON_ENDPOINTS = {
  LIST: '/coupon/list',
  AVAILABLE: '/coupon/available',
  USE: '/coupon/use',
  VALIDATE: '/coupon/validate',
  MEMBER_COUPONS: '/coupon/memberCoupons',
  STATISTICS: '/coupon/statistics',
  DETAIL: '/coupon/detail',
  UNUSED: '/coupon/unused',
  NEAR_EXPIRY: '/coupon/nearExpiry',
} as const

// 统一API端点导出
export const API_ENDPOINTS = {
  // 系统测试
  HEALTH_CHECK: SYSTEM_ENDPOINTS.HEALTH_CHECK,
  SYSTEM_INFO: SYSTEM_ENDPOINTS.SYSTEM_INFO,
  AUTH_TEST: SYSTEM_ENDPOINTS.AUTH_TEST,
  
  // 会员
  MEMBER_LOGIN: MEMBER_ENDPOINTS.LOGIN,
  MEMBER_LOGIN_BY_CODE: MEMBER_ENDPOINTS.LOGIN_BY_CODE,
  MEMBER_GUEST_LOGIN: MEMBER_ENDPOINTS.GUEST_LOGIN,
  MEMBER_LOGOUT: MEMBER_ENDPOINTS.LOGOUT,
  MEMBER_SEND_CODE: MEMBER_ENDPOINTS.SEND_CODE,
  MEMBER_REFRESH_ACTIVITY: MEMBER_ENDPOINTS.REFRESH_ACTIVITY,
  MEMBER_INFO: MEMBER_ENDPOINTS.INFO,
  MEMBER_CHECK_LOGIN: MEMBER_ENDPOINTS.CHECK_LOGIN,
  MEMBER_GUEST_INFO: MEMBER_ENDPOINTS.GUEST_INFO,
  MEMBER_CURRENT_USER: MEMBER_ENDPOINTS.CURRENT_USER,
  MEMBER_CHECK_SESSION: MEMBER_ENDPOINTS.CHECK_SESSION,
  MEMBER_GET_CODE: MEMBER_ENDPOINTS.GET_CODE,
  MEMBER_GENERATE_QR: MEMBER_ENDPOINTS.GENERATE_QR,
  MEMBER_BALANCE_INFO: MEMBER_ENDPOINTS.BALANCE_INFO,
  
  // 商品
  PRODUCT_LIST: PRODUCT_ENDPOINTS.LIST,
  PRODUCT_DETAIL: PRODUCT_ENDPOINTS.DETAIL,
  PRODUCT_SEARCH: PRODUCT_ENDPOINTS.SEARCH,
  PRODUCT_CATEGORIES: PRODUCT_ENDPOINTS.CATEGORIES,
  PRODUCT_BARCODE_SCAN: PRODUCT_ENDPOINTS.BARCODE_SCAN,
  PRODUCT_RECOMMENDATIONS: PRODUCT_ENDPOINTS.RECOMMENDATIONS,
  PRODUCT_BRANDS: PRODUCT_ENDPOINTS.BRAND_LIST,
  PRODUCT_HOT: PRODUCT_ENDPOINTS.HOT_PRODUCTS,
  PRODUCT_NEW: PRODUCT_ENDPOINTS.NEW_PRODUCTS,
  PRODUCT_PRICE_CHECK: PRODUCT_ENDPOINTS.PRICE_CHECK,
  
  // 购物车
  CART_ADD: CART_ENDPOINTS.ADD,
  CART_REMOVE: CART_ENDPOINTS.REMOVE,
  CART_UPDATE: CART_ENDPOINTS.UPDATE,
  CART_LIST: CART_ENDPOINTS.LIST,
  CART_CLEAR: CART_ENDPOINTS.CLEAR,
  CART_COUNT: CART_ENDPOINTS.COUNT,
  CART_SUMMARY: CART_ENDPOINTS.SUMMARY,
  CART_VALIDATE: CART_ENDPOINTS.VALIDATE,
  CART_AVAILABLE_COUPONS: CART_ENDPOINTS.AVAILABLE_COUPONS,
  CART_CALCULATE: CART_ENDPOINTS.CALCULATE,
  
  // 订单
  ORDER_CREATE: ORDER_ENDPOINTS.CREATE,
  ORDER_CREATE_QUICK: ORDER_ENDPOINTS.CREATE_QUICK,
  ORDER_CREATE_FROM_CART: ORDER_ENDPOINTS.CREATE_FROM_CART,
  ORDER_DETAIL: ORDER_ENDPOINTS.DETAIL,
  ORDER_LIST: ORDER_ENDPOINTS.LIST,
  ORDER_HISTORY: ORDER_ENDPOINTS.HISTORY,
  ORDER_GUEST_HISTORY: ORDER_ENDPOINTS.GUEST_HISTORY,
  ORDER_CANCEL: ORDER_ENDPOINTS.CANCEL,
  ORDER_CONFIRM: ORDER_ENDPOINTS.CONFIRM,
  ORDER_STATUS: ORDER_ENDPOINTS.STATUS,
  ORDER_CALCULATE: ORDER_ENDPOINTS.CALCULATE,
  ORDER_PREVIEW: ORDER_ENDPOINTS.PREVIEW,
  ORDER_VALIDATE_STOCK: ORDER_ENDPOINTS.VALIDATE_STOCK,
  ORDER_PAYMENT_SUCCESS: ORDER_ENDPOINTS.PAYMENT_SUCCESS,
  ORDER_PAYMENT_FAILED: ORDER_ENDPOINTS.PAYMENT_FAILED,
  
  // 支付
  PAYMENT_QR_WECHAT: PAYMENT_ENDPOINTS.WECHAT_QR,
  PAYMENT_QR_ALIPAY: PAYMENT_ENDPOINTS.ALIPAY_QR,
  PAYMENT_SCAN_PAY: PAYMENT_ENDPOINTS.SCAN_PAY,
  PAYMENT_STATUS: PAYMENT_ENDPOINTS.STATUS,
  PAYMENT_CANCEL: PAYMENT_ENDPOINTS.CANCEL,
  PAYMENT_REFUND: PAYMENT_ENDPOINTS.REFUND,
  PAYMENT_METHODS: PAYMENT_ENDPOINTS.METHODS,
  PAYMENT_CONFIG: PAYMENT_ENDPOINTS.CONFIG,
  
  // 优惠券
  COUPON_LIST: COUPON_ENDPOINTS.LIST,
  COUPON_AVAILABLE: COUPON_ENDPOINTS.AVAILABLE,
  COUPON_USE: COUPON_ENDPOINTS.USE,
  COUPON_VALIDATE: COUPON_ENDPOINTS.VALIDATE,
  COUPON_MEMBER_COUPONS: COUPON_ENDPOINTS.MEMBER_COUPONS,
  COUPON_STATISTICS: COUPON_ENDPOINTS.STATISTICS,
  COUPON_DETAIL: COUPON_ENDPOINTS.DETAIL,
  COUPON_UNUSED: COUPON_ENDPOINTS.UNUSED,
  COUPON_NEAR_EXPIRY: COUPON_ENDPOINTS.NEAR_EXPIRY,
} as const 